openapi: 3.0.3

info:
  title: オレオレAPI
  description: >
    Yeah!
    テスト段階中
  version: 1.0.0

servers:
  - url: http://localhost/???
    description: Local server

tags:
  - name: 漫画一覧
    description: 管理側のメール送信API

paths:
  /reserve/supersaas/send:
    $ref: './paths/mail.yml#/send'

components:
  schemas:
    SuperSaasMailRequest:
      $ref: './components/schemas/mailRequest.yml'
    SuccessResponse:
      $ref: './components/schemas/successResponse.yml'
    ErrorResponse:
      $ref: './components/schemas/errorResponse.yml'
